# Generated by Django 3.1.1 on 2023-02-15 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalExpences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('expence', models.CharField(max_length=50)),
                ('repeated', models.BooleanField()),
                ('repeating_span', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarter', 'Quarter'), ('twice', 'Twice'), ('yearly', 'Yearly')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('image', models.FileField(null=True, upload_to='./static/pictures/animals')),
                ('lifespan', models.IntegerField(null=True)),
                ('in_expences', models.ManyToManyField(related_name='in_expences', to='Animals.AnimalExpences')),
                ('out_expences', models.ManyToManyField(related_name='out_expences', to='Animals.AnimalExpences')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(verbose_name='Months')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.farm')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Animals.animaltypes')),
            ],
        ),
    ]
