# Generated by Django 3.1.1 on 2023-02-19 10:34

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Farm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpencesAndProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('expence', models.CharField(max_length=50)),
                ('repeated', models.BooleanField()),
                ('repeating_span', models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarter', 'Quarter'), ('twice', 'Twice'), ('yearly', 'Yearly')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='type')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/pictures/animals/')),
                ('lifespan', models.IntegerField(null=True)),
                ('icon', models.CharField(max_length=25)),
                ('expences', models.ManyToManyField(related_name='expences', to='Animals.ExpencesAndProduct')),
                ('product', models.ManyToManyField(related_name='product', to='Animals.ExpencesAndProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField(verbose_name='Months')),
                ('image', models.FileField(blank=True, null=True, upload_to='static/pictures/animals/')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.farm')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Animals.animaltypes')),
            ],
        ),
    ]
