# Generated by Django 3.1.1 on 2023-02-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animaltypes',
            name='icon',
        ),
    ]
