# Generated by Django 3.1.1 on 2023-02-15 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalexpences',
            name='repeating_span',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarter', 'Quarter'), ('twice', 'Twice'), ('yearly', 'Yearly')], max_length=50, null=True),
        ),
    ]
