# Generated by Django 3.1.1 on 2023-02-19 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0002_units'),
        ('Animals', '0002_remove_animaltypes_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalExpences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Animals.animal')),
                ('expence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Animals.expencesandproduct')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.units')),
            ],
        ),
    ]
