# Generated by Django 3.1.1 on 2023-02-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0002_auto_20230215_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltypes',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='./static/pictures/animals'),
        ),
    ]
