# Generated by Django 3.1.1 on 2023-02-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0003_auto_20230215_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animaltypes',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='./assets/pictures/animals'),
        ),
    ]
