# Generated by Django 3.1.1 on 2023-02-19 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0003_animalexpences'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalexpences',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
