# Generated by Django 3.1.1 on 2023-02-19 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0002_units'),
        ('Animals', '0005_animalproducts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalexpences',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Farm.units'),
        ),
        migrations.AlterField(
            model_name='animalproducts',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Farm.units'),
        ),
    ]
