# Generated by Django 3.1.1 on 2023-02-19 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0003_expenceunits'),
        ('Animals', '0007_auto_20230219_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalexpences',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.expenceunits'),
        ),
        migrations.AlterField(
            model_name='animalproducts',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.expenceunits'),
        ),
    ]
