# Generated by Django 3.1.1 on 2023-02-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0004_auto_20230219_1838'),
        ('Animals', '0008_auto_20230219_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalproducts',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.productunits'),
        ),
    ]
