# Generated by Django 3.1.1 on 2023-02-19 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0009_auto_20230219_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animal',
            old_name='name',
            new_name='animal',
        ),
    ]
