# Generated by Django 3.1.1 on 2023-02-19 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0006_delete_farmgroups'),
        ('Animals', '0010_auto_20230219_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=100)),
                ('animals', models.ManyToManyField(related_name='animals', to='Animals.Animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.farm')),
            ],
        ),
    ]
