# Generated by Django 3.1.1 on 2023-02-19 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0011_animalgroups'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalgroups',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Animals.animaltypes'),
            preserve_default=False,
        ),
    ]
