# Generated by Django 3.1.1 on 2023-02-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0012_animalgroups_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='animalexpences',
            unique_together={('animal', 'expence', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='animalproducts',
            unique_together={('animal', 'product', 'date')},
        ),
    ]
