# Generated by Django 3.1.1 on 2023-02-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Animals', '0013_auto_20230219_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animalexpences',
            name='qty',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='animalproducts',
            name='qty',
            field=models.CharField(max_length=5),
        ),
    ]
