# Generated by Django 3.1.1 on 2023-02-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('flow', models.IntegerField(auto_created=True, blank=True, null=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('caption', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.FileField(upload_to='static/pictures/slider/')),
            ],
        ),
    ]
