# Generated by Django 3.1.1 on 2023-02-15 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainPageSlider',
            fields=[
                ('flow', models.IntegerField(auto_created=True)),
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('caption', models.CharField(max_length=500)),
                ('image', models.FileField(blank=True, null=True, upload_to='./assets/pictures/slider')),
            ],
        ),
    ]
