# Generated by Django 3.1.1 on 2023-02-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_auto_20230216_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpageslider',
            name='image',
            field=models.FileField(upload_to='static/pictures/slider/'),
        ),
    ]
