# Generated by Django 3.1.1 on 2023-02-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=50)),
                ('phone', models.BigIntegerField(null=True)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(max_length=250)),
            ],
        ),
    ]
