# Generated by Django 3.1.1 on 2023-02-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0003_expenceunits'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Units',
            new_name='ProductUnits',
        ),
    ]
