# Generated by Django 3.1.1 on 2023-02-19 13:53

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0004_auto_20230219_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expenceunits',
            old_name='name',
            new_name='unit',
        ),
        migrations.RenameField(
            model_name='farm',
            old_name='name',
            new_name='farm',
        ),
        migrations.RenameField(
            model_name='productunits',
            old_name='name',
            new_name='unit',
        ),
        migrations.AlterField(
            model_name='farm',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='farm'),
        ),
        migrations.CreateModel(
            name='FarmGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=100)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.farm')),
            ],
        ),
    ]
