# Generated by Django 3.1.1 on 2023-02-19 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0005_auto_20230219_1853'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FarmGroups',
        ),
    ]
