# Generated by Django 3.1.1 on 2023-02-21 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Farm', '0006_delete_farmgroups'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productunits',
            unique_together={('farm', 'unit')},
        ),
        migrations.CreateModel(
            name='FarmGalery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.FileField(blank=True, null=True, upload_to='static/pictures/farm/gallery')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Farm.farm')),
            ],
        ),
    ]
